spring:
  application:
    name: st-config-server
  profiles:
    active: "develop"
    
---

spring:
  profiles: develop
  cloud:
    config:
      server:
        git:
          uri: http://192.168.98.230/sistema-transicion/configuration/st-configuration-properties.git
          username: USERNAME
          password: PASSWORD
          default-label: develop

server:
  port: 8889

---

spring:
  profiles: production
  cloud:
    config:
      server:
        git:
          uri: http://192.168.98.230/sistema-transicion/configuration/st-configuration-properties.git
          username: USERNAME
          password: PASSWORD
          default-label: master

server:
  port: 8890