spring:
  application:
    name: st-config-server
  profiles:
    active: "aws"
    
---

spring:
  profiles: develop
  cloud:
    config:
      server:
        git:
          uri: HOSTNAME
          username: USERNAME
          password: PASSWORD
          default-label: develop

server:
  port: 8889

---

spring:
  profiles: production
  cloud:
    config:
      server:
        git:
          uri: HOSTNAME
          username: USERNAME
          password: PASSWORD
          default-label: master

server:
  port: 8890

---

spring:
  profiles: aws
  cloud:
    config:
      server:
        git:
          uri: HOSTNAME
          username: USERNAME
          password: PASSWORD
          default-label: aws

server:
  port: 8890